language: python

cache:
  - pip
  - ccache

matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.6"


install:
  - pip install -U pip wheel
  - pip install -r ./test/test_requirements.txt
  # unable to install pytorch 0.3.0 as https://github.com/pytorch/pytorch/issues/4178
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post2-cp27-cp27mu-manylinux1_x86_64.whl;
    else
          pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post2-cp36-cp36m-manylinux1_x86_64.whl;
    fi

script:
  # TODO test coding style?
  - flake8 src test
  - autopep8 *.py  --global-config .pep8 --diff --max-line-length 120 | tee check_autopep8
  - test ! -s check_autopep8

sudo: false

addons:
  apt:
    packages:
      - cmake
      - python-dev
      - python3-dev
